name: CI/CD Pipeline

on:
  push:
    paths:
      - "index.html"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.MY_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.MY_DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.MY_DOCKER_USERNAME }}/html-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.MY_DOCKER_USERNAME }}/html-app:latest

      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/my_swarm_key
          chmod 600 ~/.ssh/my_swarm_key

      - name: SSH to PWD - Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.MY_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.MY_DOCKER_PASSWORD }}
        run: |
          ssh -tt -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -i ~/.ssh/my_swarm_key root@172-18-0-96-csmrg32im2rgO08oouvg@direct.labs.play-with-docker.com "docker login -u '${DOCKER_USERNAME}' -p '${DOCKER_PASSWORD}'"

      - name: SSH to PWD - Create Stack File
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/my_swarm_key root@172-18-0-96-csmrg32im2rgO08oouvg@direct.labs.play-with-docker.com "echo \"version: '3.8'\nservices:\n  web:\n    image: ${DOCKER_USERNAME}/html-app:latest\n    deploy:\n      placement:\n        constraints: [node.role == worker]\n    ports:\n      - 80:80\" > stack.yml"

      - name: SSH to PWD - Deploy Stack
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/my_swarm_key root@172-18-0-96-csmrg32im2rgO08oouvg@direct.labs.play-with-docker.com "docker stack deploy -c stack.yml webapp"
