name: CI/CD Pipeline

on:
  push:
    paths:
      - "index.html"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.MY_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.MY_DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.MY_DOCKER_USERNAME }}/html-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.MY_DOCKER_USERNAME }}/html-app:latest

      - name: Generate SSH key
        run: ssh-keygen -t ed25519 -P "" -f ~/.ssh/id_ed25519

      - name: Copy SSH key
        run: cat ~/.ssh/id_ed25519.pub
