name: CI/CD Pipeline

on:
  push:
    paths:
      - "index.html"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.MY_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.MY_DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.MY_DOCKER_USERNAME }}/html-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.MY_DOCKER_USERNAME }}/html-app:latest

      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/my_swarm_key
          chmod 600 ~/.ssh/my_swarm_key

      - name: Connect to Swarm Manager and Deploy
        env:
          DOCKER_USERNAME: ${{ secrets.MY_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.MY_DOCKER_PASSWORD }}
        run: |
          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/my_swarm_key root@172-18-0-96-csmrg32im2rgO08oouvg@direct.labs.play-with-docker.com << 'EOF'
            docker login -u "${MY_DOCKER_USERNAME}" -p "${MY_DOCKER_PASSWORD}"
            echo "version: '3.8'
            services:
              web:
                image: ${MY_DOCKER_USERNAME}/html-app:latest
                deploy:
                  placement:
                    constraints: [node.role == worker]
                ports:
                  - 80:80
            " > stack.yml
            docker stack deploy -c stack.yml webapp
          EOF
